
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Apr 13 17:15:02 ICT 2018
//----------------------------------------------------

package src;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int INTDEF = 26;
  public static final int TIMES = 5;
  public static final int AND = 23;
  public static final int NOTEQ = 18;
  public static final int PLUS = 3;
  public static final int INT = 29;
  public static final int OR = 24;
  public static final int RPAREN = 8;
  public static final int LESSEREQ = 20;
  public static final int THEN = 11;
  public static final int BOOLEANDEF = 28;
  public static final int SEMI = 2;
  public static final int WHILE = 13;
  public static final int NOT = 25;
  public static final int END = 16;
  public static final int GREATER = 21;
  public static final int IF = 10;
  public static final int LPAREN = 7;
  public static final int ID = 32;
  public static final int ASS = 9;
  public static final int DO = 14;
  public static final int BEGIN = 15;
  public static final int BOOLEAN = 31;
  public static final int FLOAT = 30;
  public static final int EOF = 0;
  public static final int DIVIDE = 6;
  public static final int GREATEREQ = 22;
  public static final int MINUS = 4;
  public static final int PRINT = 12;
  public static final int error = 1;
  public static final int LESSER = 19;
  public static final int EQ = 17;
  public static final int FLOATDEF = 27;
}

